[tool.briefcase]
project_name = "Attendance Taker"
bundle = "com.attendancetaker"
version = "1.0"
url = "https://github.com/advin4603/Attendance-Taker"
license = "MIT license"
author = 'Ayan Datta'
author_email = "advin4603@gmail.com"

[tool.briefcase.app.attendancetaker]
formal_name = "Attendance Taker"
description = "Determines absentees and unrecognized people from a list of students."
sources = ['src/attendancetaker']
requires = ['pyside2==5.15.0', 'openpyxl==3.0.5', "pyperclip==1.8.0"]
icon = "Resources/Vexels-Office-Clipboard"
installer_icon = "Resources/Vexels-Office-Clipboard"
installer_background = "Resources/paper"

[tool.briefcase.app.attendancetaker.macOS]
requires = []

[tool.briefcase.app.attendancetaker.linux]
requires = []
system_requires = []

[tool.briefcase.app.attendancetaker.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.attendancetaker.iOS]
requires = []

[tool.briefcase.app.attendancetaker.android]
requires = []
